#!/bin/bash
water=$(echo $WATER | tr behlnort 0123456); stir=$(echo $STIR | tr behlnort 0123456); sum=$((water + stir)); bestchol=$(echo "obase=7; ibase=10; $sum" | bc | tr 0123456 bestchol); echo $bestchol
